### ISSUE TITLE
travis CI build failing

### ISSUE THREAD

**Issue by rmallah** [lirios/repotools#1]
Travis CI build seems to be failing for some syntax error in docker-travis.sh

looks like extra braces in below code is responsible

```
    CONFIG_BUILD_SCRIPTS=($(travis_yml arch script))
    CONFIG_PACKAGES=($(travis_yml arch packages))
    CONFIG_REPOS=($(travis_yml arch repos))
    CONFIG_ARTIFACTS=($(travis_yml arch artifacts))
```

Eg:
https://travis-ci.org/lirios/fluid/jobs/300280440

The command "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash" exited with 1.

Done. Your build exited with 1.

**Comment by plfiorini** [comment]
The container needed to be updated: now https://travis-ci.org/lirios/fluid/jobs/300280440 is fine
